project:
  type: book  
  output-dir: docs

book:
  title: "Evaluation of Not Safe For Work"
  author: "Jia Yee Wong"
  page-footer:
    left: "Copyright 2025, Jia Yee Wong"
  chapters:
    - index.qmd  #this is my exec summary because I when I delete my index.qmd an error will appear
    - intro.qmd
    - methods.qmd
    - results.qmd
    - conclusion.qmd
    - references.qmd
  appendices:
    - draft-exec-summary.qmd
    - draft-intro-conclusions.qmd
    - draft-data-doc.qmd
    - draft-results.qmd
    - draft-conclusion.qmd

bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme: cosmo
  pdf:
    documentclass: scrreprt



